export const legacyThemeAliases: Record<string, string> = {
  "academia-classical": "academia",
  "art-deco-luxe": "art-deco",
  "bauhaus-geometric": "swiss-minimalist",
  "botanical-editorial": "botanical",
  "clay-white-landscape": "clay-white-landscape-mockup",
  "comic-art": "comic-art-illustration",
  "comic-art-like": "comic-art-illustration",
  "cyberpunk-neon": "cyberpunk",
  "default-high-agency": "asymmetry-grid-layouts",
  "double-light": "double-light-photography",
  "futuristic-neon": "futuristic-neon-illustration",
  "lineart": "lineart-illustration",
  "material": "material-design",
  "maximalism-collage": "maximalist",
  "mbe": "mbe-illustration",
  "mbe-style-illustration": "mbe-illustration",
  "minimalist-editorial": "editorial-minimalism",
  "premium-polish": "premium-monochrome",
  "professional-corporate": "bento-grid",
  "sketch-wireframe": "sketch",
  "structured-technical": "terminal",
  "swiss": "swiss-minimalist",
  "terminal-interface": "terminal",
  "vaporwave-dreamscape": "vaporwave",
  "web3-orange-ledger": "cyberpunk",
};
